using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Geometry;
using Autodesk.AutoCAD.Runtime;
using AcApp=Autodesk.AutoCAD.ApplicationServices.Application;
namespace RofamaCad.Structural;
public sealed class AssociativeEnvelopeCommands
{
 [CommandMethod("RFATUALIZARENVELOPE")]
 public void Run(){
  var d=AcApp.DocumentManager.MdiActiveDocument;var db=d.Database;using var tr=db.TransactionManager.StartTransaction();var mat=MaterialCommands.Read(db,tr);if(!mat.HasValue){d.Editor.WriteMessage("\nDefina RFMATERIAL.");return;}var cfg=DiagramSettingsCommands.Read(db,tr);Ensure(tr,db,"RF-EST-ENV-V");Ensure(tr,db,"RF-EST-ENV-M");Ensure(tr,db,"RF-EST-ENV-D");var ms=(BlockTableRecord)tr.GetObject(SymbolUtilityServices.GetBlockModelSpaceId(db),OpenMode.ForWrite);var beams=ms.Cast<ObjectId>().ToArray();int n=0;
  foreach(var id in beams){if(tr.GetObject(id,OpenMode.ForRead) is not Line b||b.Layer!="RF-EST-VIGA"||b.ExtensionDictionary.IsNull)continue;var dic=(DBDictionary)tr.GetObject(b.ExtensionDictionary,OpenMode.ForRead);var spans=Spans(dic,tr);if(spans==null)continue;var curves=new List<(string name,double[] q,double[] u,double[] ef,List<BeamPostProcessor.PointLoad> pts)>();foreach(DBDictionaryEntry x in dic)if(x.Key.StartsWith("ROFAMA_COMB_RESULT_")){var a=((Xrecord)tr.GetObject(x.Value,OpenMode.ForRead)).Data?.AsArray();if(a==null)continue;string name=Convert.ToString(a[0].Value)??x.Key;int nd=Convert.ToInt32(a[1].Value);var terms=LoadCombinationService.Read(db,tr,name);if(terms==null)continue;var q=new double[spans.Length];var pts=new List<BeamPostProcessor.PointLoad>();bool ok=true;foreach(var t in terms){var z=LoadCaseDataService.ReadSpans(b,tr,t.Case);if(z==null||z.Length!=q.Length){ok=false;break;}for(int i=0;i<q.Length;i++)q[i]+=t.Factor*z[i];pts.AddRange(LoadCaseDataService.ReadPoints(b,tr,t.Case).Select(p=>new BeamPostProcessor.PointLoad(p.Element,p.X,t.Factor*p.P)));}if(!ok)continue;curves.Add((name,q,a.Skip(2).Take(nd).Select(z=>Convert.ToDouble(z.Value)).ToArray(),a.Skip(2+2*nd).Select(z=>Convert.ToDouble(z.Value)).ToArray(),pts));}if(curves.Count==0)continue;GeneratedGraphicsService.EraseFor(ms,tr,b.Handle.ToString());var grid=curves.SelectMany(c=>BeamFieldEvaluator.Grid(spans,c.pts)).OrderBy(x=>x).DistinctBy(x=>Math.Round(x,8)).ToList();var env=new List<ContinuousEnvelopeService.EnvelopePoint>();foreach(var x in grid){var z=curves.Select(c=>(c.name,v:BeamFieldEvaluator.At(spans,c.q,c.u,c.ef,c.pts,x))).ToList();var v0=z.MinBy(a=>a.v.V)!;var v1=z.MaxBy(a=>a.v.V)!;var m0=z.MinBy(a=>a.v.M)!;var m1=z.MaxBy(a=>a.v.M)!;var d0=z.MinBy(a=>a.v.D)!;var d1=z.MaxBy(a=>a.v.D)!;env.Add(new(x,v0.v.V,v1.v.V,v0.name,v1.name,m0.v.M,m1.v.M,m0.name,m1.name,d0.v.D,d1.v.D,d0.name,d1.name));}Draw(ms,tr,b,env.Select(x=>(x.X,x.VMin,x.VMax)),"RF-EST-ENV-V",cfg.VScale,"ENV_V");Draw(ms,tr,b,env.Select(x=>(x.X,x.MMin,x.MMax)),"RF-EST-ENV-M",cfg.MScale,"ENV_M");Draw(ms,tr,b,env.Select(x=>(x.X,x.DMin,x.DMax)),"RF-EST-ENV-D",cfg.DScale,"ENV_D");n++;}
  tr.Commit();d.Editor.WriteMessage($"\nEnvelope associativo atualizado em {n} viga(s).");
 }
 static void Draw(BlockTableRecord ms,Transaction tr,Line b,IEnumerable<(double x,double lo,double hi)> values,string layer,double scale,string kind){var a=values.ToList();var dir=(b.EndPoint-b.StartPoint).GetNormal();var normal=new Vector3d(-dir.Y,dir.X,0);foreach(var upper in new[]{false,true}){var pl=new Polyline();for(int i=0;i<a.Count;i++){double y=upper?a[i].hi:a[i].lo;var p=b.StartPoint+dir*a[i].x+normal*y*scale;pl.AddVertexAt(i,new Point2d(p.X,p.Y),0,0,0);}pl.Layer=layer;ms.AppendEntity(pl);tr.AddNewlyCreatedDBObject(pl,true);GeneratedGraphicsService.Tag(pl,tr,b.Handle.ToString(),kind);}}
 static double[]? Spans(DBDictionary d,Transaction tr){if(!d.Contains("ROFAMA_ANALYTICAL_SPANS"))return null;return ((Xrecord)tr.GetObject(d.GetAt("ROFAMA_ANALYTICAL_SPANS"),OpenMode.ForRead)).Data!.AsArray().Skip(1).Select(x=>Convert.ToDouble(x.Value)).ToArray();}
 static void Ensure(Transaction tr,Database db,string name){var lt=(LayerTable)tr.GetObject(db.LayerTableId,OpenMode.ForRead);if(lt.Has(name))return;lt.UpgradeOpen();var l=new LayerTableRecord{Name=name};lt.Add(l);tr.AddNewlyCreatedDBObject(l,true);}
}
