using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.Runtime;
using AcApp=Autodesk.AutoCAD.ApplicationServices.Application;
namespace RofamaCad.Structural;
public sealed class CombinationAnalysisCommands
{
 [CommandMethod("RFANALISARCOMBINACAO")]
 public void Run(){
  var d=AcApp.DocumentManager.MdiActiveDocument;var db=d.Database;var ed=d.Editor;var pn=ed.GetString(new PromptStringOptions("\nNome da combinação: "){AllowSpaces=false});if(pn.Status!=PromptStatus.OK)return;string name=pn.StringResult.Trim().ToUpperInvariant();using var tr=db.TransactionManager.StartTransaction();var terms=LoadCombinationService.Read(db,tr,name);var mat=MaterialCommands.Read(db,tr);if(terms==null||terms.Count==0){ed.WriteMessage("\nCombinação não encontrada.");return;}if(!mat.HasValue){ed.WriteMessage("\nDefina RFMATERIAL.");return;}var ms=(BlockTableRecord)tr.GetObject(SymbolUtilityServices.GetBlockModelSpaceId(db),OpenMode.ForWrite);int ok=0,miss=0,bad=0;
  foreach(ObjectId id in ms){if(tr.GetObject(id,OpenMode.ForRead) is not Line b||b.Layer!="RF-EST-VIGA"||b.ExtensionDictionary.IsNull)continue;try{var s=Spans(b,tr);var bc=BC(b,tr);if(s==null||bc==null){miss++;continue;}var q=new double[s.Length];var pts=new List<UnifiedBeamSolver.PointLoad>();bool complete=true;foreach(var t in terms){var qc=LoadCaseDataService.ReadSpans(b,tr,t.Case);if(qc==null||qc.Length!=s.Length){complete=false;break;}for(int i=0;i<s.Length;i++)q[i]+=t.Factor*qc[i];pts.AddRange(LoadCaseDataService.ReadPoints(b,tr,t.Case).Select(p=>new UnifiedBeamSolver.PointLoad(p.Element,p.X,t.Factor*p.P)));}if(!complete){miss++;continue;}var sec=Pair(b,tr,"ROFAMA_PRESIZE");double bw=sec?.A??.15,h=sec?.B??.40,I=bw*Math.Pow(h,3)/12,E=mat.Value.E*1000;var rel=ReleaseModelService.Flags(s.Length,ReleaseModelService.Parse(b,tr));var r=UnifiedBeamSolver.Solve(s,s.Select(_=>E*I).ToArray(),q,bc.Value.V,bc.Value.R,rel,pts);Write(b,tr,name,r);ok++;}catch(InvalidOperationException){bad++;}}
  tr.Commit();ed.WriteMessage($"\nCombinação {name}: {ok} viga(s) analisada(s), {miss} incompleta(s), {bad} instável(is).");
 }
 static double[]? Spans(Entity e,Transaction tr){var d=(DBDictionary)tr.GetObject(e.ExtensionDictionary,OpenMode.ForRead);if(!d.Contains("ROFAMA_ANALYTICAL_SPANS"))return null;return ((Xrecord)tr.GetObject(d.GetAt("ROFAMA_ANALYTICAL_SPANS"),OpenMode.ForRead)).Data!.AsArray().Skip(1).Select(x=>Convert.ToDouble(x.Value)).ToArray();}
 static(bool[] V,bool[] R)? BC(Entity e,Transaction tr){var d=(DBDictionary)tr.GetObject(e.ExtensionDictionary,OpenMode.ForRead);if(!d.Contains("ROFAMA_BOUNDARY"))return null;var a=((Xrecord)tr.GetObject(d.GetAt("ROFAMA_BOUNDARY"),OpenMode.ForRead)).Data?.AsArray();if(a==null)return null;int n=Convert.ToInt32(a[0].Value);var v=new bool[n];var r=new bool[n];for(int i=0;i<n;i++){v[i]=Convert.ToInt32(a[1+2*i].Value)!=0;r[i]=Convert.ToInt32(a[2+2*i].Value)!=0;}return(v,r);}
 static(double A,double B)? Pair(Entity e,Transaction tr,string k){var d=(DBDictionary)tr.GetObject(e.ExtensionDictionary,OpenMode.ForRead);if(!d.Contains(k))return null;var a=((Xrecord)tr.GetObject(d.GetAt(k),OpenMode.ForRead)).Data?.AsArray();return a?.Length>=2?(Convert.ToDouble(a[0].Value),Convert.ToDouble(a[1].Value)):null;}
 static void Write(Entity e,Transaction tr,string name,UnifiedBeamSolver.Result r){e.UpgradeOpen();var d=(DBDictionary)tr.GetObject(e.ExtensionDictionary,OpenMode.ForWrite);string k="ROFAMA_COMB_RESULT_"+new string(name.Where(c=>char.IsLetterOrDigit(c)||c=='_').ToArray());Xrecord x;if(d.Contains(k))x=(Xrecord)tr.GetObject(d.GetAt(k),OpenMode.ForWrite);else{x=new Xrecord();d.SetAt(k,x);tr.AddNewlyCreatedDBObject(x,true);}var a=new List<TypedValue>{new((int)DxfCode.Text,name),new((int)DxfCode.Int32,r.Displacement.Length)};a.AddRange(r.Displacement.Select(z=>new TypedValue((int)DxfCode.Real,z)));a.AddRange(r.Reaction.Select(z=>new TypedValue((int)DxfCode.Real,z)));a.AddRange(r.EndForce.Select(z=>new TypedValue((int)DxfCode.Real,z)));x.Data=new ResultBuffer(a.ToArray());}
}
