using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Geometry;
using Autodesk.AutoCAD.Runtime;
using AcApp=Autodesk.AutoCAD.ApplicationServices.Application;
namespace RofamaCad.Structural;
public sealed class ContinuousEnvelopeCommands
{
 [CommandMethod("RFENVELOPECONTINUO")]
 public void Run(){
  var d=AcApp.DocumentManager.MdiActiveDocument;var db=d.Database;using var tr=db.TransactionManager.StartTransaction();Ensure(tr,db,"RF-EST-ENV-V");Ensure(tr,db,"RF-EST-ENV-M");Ensure(tr,db,"RF-EST-ENV-D");var cfg=DiagramSettingsCommands.Read(db,tr);var mat=MaterialCommands.Read(db,tr);if(!mat.HasValue){d.Editor.WriteMessage("\nDefina RFMATERIAL.");return;}var ms=(BlockTableRecord)tr.GetObject(SymbolUtilityServices.GetBlockModelSpaceId(db),OpenMode.ForWrite);var ids=ms.Cast<ObjectId>().ToArray();int done=0;
  foreach(var id in ids){if(tr.GetObject(id,OpenMode.ForRead) is not Line b||b.Layer!="RF-EST-VIGA"||b.ExtensionDictionary.IsNull)continue;var dic=(DBDictionary)tr.GetObject(b.ExtensionDictionary,OpenMode.ForRead);var spans=Spans(dic,tr);if(spans==null)continue;var sec=Pair(dic,tr,"ROFAMA_PRESIZE");double bw=sec?.A??.15,h=sec?.B??.40,EI=mat.Value.E*1000*bw*Math.Pow(h,3)/12;var curves=new List<ContinuousEnvelopeService.Curve>();
   foreach(DBDictionaryEntry x in dic)if(x.Key.StartsWith("ROFAMA_COMB_RESULT_")){var a=((Xrecord)tr.GetObject(x.Value,OpenMode.ForRead)).Data?.AsArray();if(a==null||a.Length<2)continue;string name=Convert.ToString(a[0].Value)??x.Key;int nd=Convert.ToInt32(a[1].Value);var u=a.Skip(2).Take(nd).Select(z=>Convert.ToDouble(z.Value)).ToArray();var ef=a.Skip(2+2*nd).Select(z=>Convert.ToDouble(z.Value)).ToArray();var terms=LoadCombinationService.Read(db,tr,name);if(terms==null)continue;var q=new double[spans.Length];var pts=new List<BeamPostProcessor.PointLoad>();bool complete=true;foreach(var t in terms){var qc=LoadCaseDataService.ReadSpans(b,tr,t.Case);if(qc==null||qc.Length!=spans.Length){complete=false;break;}for(int i=0;i<q.Length;i++)q[i]+=t.Factor*qc[i];pts.AddRange(LoadCaseDataService.ReadPoints(b,tr,t.Case).Select(p=>new BeamPostProcessor.PointLoad(p.Element,p.X,t.Factor*p.P)));}if(!complete)continue;curves.Add(new(name,BeamPostProcessor.Sample(spans,spans.Select(_=>EI).ToArray(),q,u,ef,pts,50)));}
   if(curves.Count==0)continue;var env=ContinuousEnvelopeService.Build(curves);DrawPair(ms,tr,b,env.Select(x=>(x.X,x.VMin,x.VMax)).ToList(),"RF-EST-ENV-V",cfg.VScale);DrawPair(ms,tr,b,env.Select(x=>(x.X,x.MMin,x.MMax)).ToList(),"RF-EST-ENV-M",cfg.MScale);DrawPair(ms,tr,b,env.Select(x=>(x.X,x.DMin,x.DMax)).ToList(),"RF-EST-ENV-D",cfg.DScale);Write(b,tr,env);done++;}
  tr.Commit();d.Editor.WriteMessage($"\nEnvelope contínuo gerado para {done} viga(s), com V(x), M(x) e deformada.");
 }
 static void DrawPair(BlockTableRecord ms,Transaction tr,Line b,List<(double x,double lo,double hi)> a,string layer,double scale){var dir=(b.EndPoint-b.StartPoint).GetNormal();var n=new Vector3d(-dir.Y,dir.X,0);foreach(int which in new[]{1,2}){var pl=new Polyline();for(int i=0;i<a.Count;i++){double y=which==1?a[i].lo:a[i].hi;var p=b.StartPoint+dir*a[i].x+n*y*scale;pl.AddVertexAt(i,new Point2d(p.X,p.Y),0,0,0);}pl.Layer=layer;ms.AppendEntity(pl);tr.AddNewlyCreatedDBObject(pl,true);}}
 static double[]? Spans(DBDictionary d,Transaction tr){if(!d.Contains("ROFAMA_ANALYTICAL_SPANS"))return null;return ((Xrecord)tr.GetObject(d.GetAt("ROFAMA_ANALYTICAL_SPANS"),OpenMode.ForRead)).Data!.AsArray().Skip(1).Select(x=>Convert.ToDouble(x.Value)).ToArray();}
 static(double A,double B)? Pair(DBDictionary d,Transaction tr,string k){if(!d.Contains(k))return null;var a=((Xrecord)tr.GetObject(d.GetAt(k),OpenMode.ForRead)).Data?.AsArray();return a?.Length>=2?(Convert.ToDouble(a[0].Value),Convert.ToDouble(a[1].Value)):null;}
 static void Write(Entity e,Transaction tr,List<ContinuousEnvelopeService.EnvelopePoint> env){e.UpgradeOpen();var d=(DBDictionary)tr.GetObject(e.ExtensionDictionary,OpenMode.ForWrite);const string k="ROFAMA_CONTINUOUS_ENVELOPE";Xrecord x;if(d.Contains(k))x=(Xrecord)tr.GetObject(d.GetAt(k),OpenMode.ForWrite);else{x=new Xrecord();d.SetAt(k,x);tr.AddNewlyCreatedDBObject(x,true);}var a=new List<TypedValue>{new((int)DxfCode.Int32,env.Count)};foreach(var p in env){a.Add(new((int)DxfCode.Real,p.X));a.Add(new((int)DxfCode.Real,p.VMin));a.Add(new((int)DxfCode.Real,p.VMax));a.Add(new((int)DxfCode.Text,p.VMinCase));a.Add(new((int)DxfCode.Text,p.VMaxCase));a.Add(new((int)DxfCode.Real,p.MMin));a.Add(new((int)DxfCode.Real,p.MMax));a.Add(new((int)DxfCode.Text,p.MMinCase));a.Add(new((int)DxfCode.Text,p.MMaxCase));a.Add(new((int)DxfCode.Real,p.DMin));a.Add(new((int)DxfCode.Real,p.DMax));a.Add(new((int)DxfCode.Text,p.DMinCase));a.Add(new((int)DxfCode.Text,p.DMaxCase));}x.Data=new ResultBuffer(a.ToArray());}
 static void Ensure(Transaction tr,Database db,string name){var lt=(LayerTable)tr.GetObject(db.LayerTableId,OpenMode.ForRead);if(lt.Has(name))return;lt.UpgradeOpen();var l=new LayerTableRecord{Name=name};lt.Add(l);tr.AddNewlyCreatedDBObject(l,true);}
}
