namespace RofamaCad.Structural;
internal static class PointLoadBeamSolver
{
 public sealed record PointLoad(int Element,double X,double P);
 public static FrameBeamSolver.Result Solve(double[] L,double[] EI,double[] W,bool[] fixV,bool[] fixR,IReadOnlyList<PointLoad> loads){
  int ne=L.Length,nn=ne+1,nd=2*nn;var K=new double[nd,nd];var F=new double[nd];var fe=new double[4*ne];
  for(int e=0;e<ne;e++){double l=L[e],k=EI[e]/Math.Pow(l,3);double[,] a={{12*k,6*l*k,-12*k,6*l*k},{6*l*k,4*l*l*k,-6*l*k,2*l*l*k},{-12*k,-6*l*k,12*k,-6*l*k},{6*l*k,2*l*l*k,-6*l*k,4*l*l*k}};double[] q={-W[e]*l/2,-W[e]*l*l/12,-W[e]*l/2,W[e]*l*l/12};foreach(var p in loads.Where(p=>p.Element==e)){double xi=Math.Clamp(p.X/l,0,1);double n1=1-3*xi*xi+2*xi*xi*xi,n2=l*(xi-2*xi*xi+xi*xi*xi),n3=3*xi*xi-2*xi*xi*xi,n4=l*(-xi*xi+xi*xi*xi);q[0]-=p.P*n1;q[1]-=p.P*n2;q[2]-=p.P*n3;q[3]-=p.P*n4;}for(int i=0;i<4;i++){fe[4*e+i]=q[i];F[2*e+i]+=q[i];for(int j=0;j<4;j++)K[2*e+i,2*e+j]+=a[i,j];}}
  var fixedDofs=new HashSet<int>();for(int i=0;i<nn;i++){if(fixV[i])fixedDofs.Add(2*i);if(fixR[i])fixedDofs.Add(2*i+1);}var free=Enumerable.Range(0,nd).Where(i=>!fixedDofs.Contains(i)).ToArray();var Kr=new double[free.Length,free.Length];var Fr=new double[free.Length];for(int i=0;i<free.Length;i++){Fr[i]=F[free[i]];for(int j=0;j<free.Length;j++)Kr[i,j]=K[free[i],free[j]];}var ur=Gauss(Kr,Fr);var u=new double[nd];for(int i=0;i<free.Length;i++)u[free[i]]=ur[i];var reac=new double[nd];for(int i=0;i<nd;i++){for(int j=0;j<nd;j++)reac[i]+=K[i,j]*u[j];reac[i]-=F[i];}var ef=new double[4*ne];for(int e=0;e<ne;e++){double l=L[e],k=EI[e]/Math.Pow(l,3);double[,] a={{12*k,6*l*k,-12*k,6*l*k},{6*l*k,4*l*l*k,-6*l*k,2*l*l*k},{-12*k,-6*l*k,12*k,-6*l*k},{6*l*k,2*l*l*k,-6*l*k,4*l*l*k}};for(int i=0;i<4;i++){for(int j=0;j<4;j++)ef[4*e+i]+=a[i,j]*u[2*e+j];ef[4*e+i]-=fe[4*e+i];}}return new(u,reac,ef);
 }
 static double[] Gauss(double[,] a,double[] b){int n=b.Length;if(n==0)return Array.Empty<double>();var m=(double[,])a.Clone();var x=(double[])b.Clone();for(int k=0;k<n;k++){int p=k;for(int i=k+1;i<n;i++)if(Math.Abs(m[i,k])>Math.Abs(m[p,k]))p=i;if(Math.Abs(m[p,k])<1e-12)throw new InvalidOperationException("Matriz singular.");if(p!=k){for(int j=k;j<n;j++){var t=m[k,j];m[k,j]=m[p,j];m[p,j]=t;}var tb=x[k];x[k]=x[p];x[p]=tb;}for(int i=k+1;i<n;i++){var f=m[i,k]/m[k,k];for(int j=k;j<n;j++)m[i,j]-=f*m[k,j];x[i]-=f*x[k];}}var r=new double[n];for(int i=n-1;i>=0;i--){var s=x[i];for(int j=i+1;j<n;j++)s-=m[i,j]*r[j];r[i]=s/m[i,i];}return r;}
}
