using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Runtime;
using AcApp=Autodesk.AutoCAD.ApplicationServices.Application;
namespace RofamaCad.Structural;
public sealed class SolverBatchComparisonCommands
{
 [CommandMethod("RFCOMPARARSOLVERSEMLOTE")]
 public void Run(){
  var d=AcApp.DocumentManager.MdiActiveDocument;var db=d.Database;var ed=d.Editor;using var tr=db.TransactionManager.StartTransaction();var cfg=SolverComparisonSettingsCommands.Read(db,tr);var mat=MaterialCommands.Read(db,tr);if(!mat.HasValue){ed.WriteMessage("\nDefina RFMATERIAL.");return;}var ms=(BlockTableRecord)tr.GetObject(SymbolUtilityServices.GetBlockModelSpaceId(db),OpenMode.ForRead);int beams=0,tests=0,pass=0,fail=0,skip=0;var worst=new List<(string beam,string comb,SolverComparisonService.Difference d)>();
  foreach(ObjectId id in ms){if(tr.GetObject(id,OpenMode.ForRead) is not Line b||b.Layer!="RF-EST-VIGA"||b.ExtensionDictionary.IsNull)continue;beams++;var dic=(DBDictionary)tr.GetObject(b.ExtensionDictionary,OpenMode.ForRead);var spans=Spans(dic,tr);var sec=Pair(dic,tr,"ROFAMA_PRESIZE");if(spans==null||sec==null){skip++;continue;}double EI=mat.Value.E*1000*sec.Value.A*Math.Pow(sec.Value.B,3)/12;var bc=BoundaryConditionCommands.Read(b,tr,spans.Length+1);var rel=ReleaseModelService.Parse(b,tr,spans.Length);string bid=StructuralIdService.Get(b,tr,$"V{beams:00}");
   foreach(DBDictionaryEntry x in dic){if(!x.Key.StartsWith("ROFAMA_COMB_RESULT_")||x.Key.StartsWith("ROFAMA_COMB_RESULT_V2_"))continue;var old=Legacy(dic,tr,x.Key);if(old==null){skip++;continue;}string name=old.Value.N;var terms=LoadCombinationService.Read(db,tr,name);if(terms==null){skip++;continue;}var q=new double[spans.Length];var pts=new List<UnifiedBeamSolver.PointLoad>();bool complete=true;foreach(var t in terms){var z=LoadCaseDataService.ReadSpans(b,tr,t.Case);if(z==null||z.Length!=q.Length){complete=false;break;}for(int i=0;i<q.Length;i++)q[i]+=t.Factor*z[i];pts.AddRange(LoadCaseDataService.ReadPoints(b,tr,t.Case).Select(p=>new UnifiedBeamSolver.PointLoad(p.Element,p.X,t.Factor*p.P)));}if(!complete){skip++;continue;}try{var v2=SolverV2Adapter.Solve(spans,spans.Select(_=>EI).ToArray(),q,bc.FixV,bc.FixR,rel,pts);StructuralSolverResultService.Write(b,tr,"ROFAMA_COMB_RESULT_V2_"+San(name),name,"UnifiedBeamSolverV2",v2.Displacement,v2.Reaction,v2.EndForce);var df=SolverComparisonService.Compare(old.Value.U,old.Value.R,old.Value.E,v2.Displacement,v2.Reaction,v2.EndForce);bool ok=df.MaxU<=cfg.U&&df.MaxR<=cfg.R&&df.MaxE<=cfg.E;tests++;if(ok)pass++;else{fail++;worst.Add((bid,name,df));}}catch(InvalidOperationException){fail++;tests++;}}
  }
  tr.Commit();ed.WriteMessage($"\nLOTE V1 x V2: vigas={beams}, comparações={tests}, dentro={pass}, divergentes={fail}, ignoradas={skip}.");foreach(var z in worst.OrderByDescending(x=>Math.Max(x.d.MaxR,x.d.MaxE)).Take(10))ed.WriteMessage($"\n{z.beam}/{z.comb}: Δu={z.d.MaxU:G5}; ΔR={z.d.MaxR:G5}; ΔE={z.d.MaxE:G5}.");}
 static(string N,double[] U,double[] R,double[] E)? Legacy(DBDictionary d,Transaction tr,string k){var a=((Xrecord)tr.GetObject(d.GetAt(k),OpenMode.ForRead)).Data?.AsArray();if(a==null||a.Length<2)return null;int n=Convert.ToInt32(a[1].Value);return(Convert.ToString(a[0].Value)??"",a.Skip(2).Take(n).Select(x=>Convert.ToDouble(x.Value)).ToArray(),a.Skip(2+n).Take(n).Select(x=>Convert.ToDouble(x.Value)).ToArray(),a.Skip(2+2*n).Select(x=>Convert.ToDouble(x.Value)).ToArray());}
 static double[]? Spans(DBDictionary d,Transaction tr){if(!d.Contains("ROFAMA_ANALYTICAL_SPANS"))return null;return ((Xrecord)tr.GetObject(d.GetAt("ROFAMA_ANALYTICAL_SPANS"),OpenMode.ForRead)).Data!.AsArray().Skip(1).Select(x=>Convert.ToDouble(x.Value)).ToArray();}
 static(double A,double B)? Pair(DBDictionary d,Transaction tr,string k){if(!d.Contains(k))return null;var a=((Xrecord)tr.GetObject(d.GetAt(k),OpenMode.ForRead)).Data?.AsArray();return a?.Length>=2?(Convert.ToDouble(a[0].Value),Convert.ToDouble(a[1].Value)):null;}
 static string San(string s)=>new string(s.Where(c=>char.IsLetterOrDigit(c)||c=='_').ToArray());
}
