using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.Runtime;
using AcApp=Autodesk.AutoCAD.ApplicationServices.Application;
namespace RofamaCad.Structural;
public sealed class SolverComparisonCommands
{
 [CommandMethod("RFCOMPARARSOLVERS")]
 public void Run(){
  var d=AcApp.DocumentManager.MdiActiveDocument;var ed=d.Editor;var pe=ed.GetEntity("\nSelecione a viga: ");if(pe.Status!=PromptStatus.OK)return;var pn=ed.GetString(new PromptStringOptions("\nNome da combinação: "){AllowSpaces=false});if(pn.Status!=PromptStatus.OK)return;string name=pn.StringResult.Trim().ToUpperInvariant(),keyOld="ROFAMA_COMB_RESULT_"+San(name);using var tr=d.Database.TransactionManager.StartTransaction();var b=tr.GetObject(pe.ObjectId,OpenMode.ForRead) as Line;if(b==null||b.ExtensionDictionary.IsNull){ed.WriteMessage("\nViga inválida.");return;}var dic=(DBDictionary)tr.GetObject(b.ExtensionDictionary,OpenMode.ForRead);if(!dic.Contains(keyOld)){ed.WriteMessage("\nResultado V1 da combinação não encontrado.");return;}var old=ReadLegacy(dic,tr,keyOld);if(old==null)return;var spans=ReadSpans(dic,tr);if(spans==null)return;var terms=LoadCombinationService.Read(d.Database,tr,name);if(terms==null){ed.WriteMessage("\nCombinação não encontrada.");return;}var q=new double[spans.Length];var pts=new List<UnifiedBeamSolver.PointLoad>();foreach(var t in terms){var z=LoadCaseDataService.ReadSpans(b,tr,t.Case);if(z==null||z.Length!=q.Length){ed.WriteMessage($"\nCaso {t.Case} incompleto.");return;}for(int i=0;i<q.Length;i++)q[i]+=t.Factor*z[i];pts.AddRange(LoadCaseDataService.ReadPoints(b,tr,t.Case).Select(p=>new UnifiedBeamSolver.PointLoad(p.Element,p.X,t.Factor*p.P)));}var mat=MaterialCommands.Read(d.Database,tr);if(!mat.HasValue){ed.WriteMessage("\nDefina RFMATERIAL.");return;}var sec=ReadPair(dic,tr,"ROFAMA_PRESIZE");if(sec==null){ed.WriteMessage("\nPré-dimensionamento ausente.");return;}double EI=mat.Value.E*1000*sec.Value.A*Math.Pow(sec.Value.B,3)/12;var bc=BoundaryConditionCommands.Read(b,tr,spans.Length+1);var rel=ReleaseModelService.Parse(b,tr,spans.Length);var v2=SolverV2Adapter.Solve(spans,spans.Select(_=>EI).ToArray(),q,bc.FixV,bc.FixR,rel,pts);StructuralSolverResultService.Write(b,tr,"ROFAMA_COMB_RESULT_V2_"+San(name),name,"UnifiedBeamSolverV2",v2.Displacement,v2.Reaction,v2.EndForce);var diff=SolverComparisonService.Compare(old.Value.U,old.Value.R,old.Value.E,v2.Displacement,v2.Reaction,v2.EndForce);var cfg=SolverComparisonSettingsCommands.Read(d.Database,tr);bool pass=diff.MaxU<=cfg.U&&diff.MaxR<=cfg.R&&diff.MaxE<=cfg.E;tr.Commit();ed.WriteMessage($"\n{name}: V1 x V2 => Δu={diff.MaxU:G6} (i={diff.UIndex}), ΔR={diff.MaxR:G6} (i={diff.RIndex}), ΔE={diff.MaxE:G6} (i={diff.EIndex}) => {(pass?"DENTRO DAS TOLERÂNCIAS":"DIVERGÊNCIA ACIMA DA TOLERÂNCIA")}.");}
 static(string N,double[] U,double[] R,double[] E)? ReadLegacy(DBDictionary d,Transaction tr,string k){var a=((Xrecord)tr.GetObject(d.GetAt(k),OpenMode.ForRead)).Data?.AsArray();if(a==null||a.Length<2)return null;int n=Convert.ToInt32(a[1].Value);return(Convert.ToString(a[0].Value)??"",a.Skip(2).Take(n).Select(x=>Convert.ToDouble(x.Value)).ToArray(),a.Skip(2+n).Take(n).Select(x=>Convert.ToDouble(x.Value)).ToArray(),a.Skip(2+2*n).Select(x=>Convert.ToDouble(x.Value)).ToArray());}
 static double[]? ReadSpans(DBDictionary d,Transaction tr){if(!d.Contains("ROFAMA_ANALYTICAL_SPANS"))return null;return ((Xrecord)tr.GetObject(d.GetAt("ROFAMA_ANALYTICAL_SPANS"),OpenMode.ForRead)).Data!.AsArray().Skip(1).Select(x=>Convert.ToDouble(x.Value)).ToArray();}
 static(double A,double B)? ReadPair(DBDictionary d,Transaction tr,string k){if(!d.Contains(k))return null;var a=((Xrecord)tr.GetObject(d.GetAt(k),OpenMode.ForRead)).Data?.AsArray();return a?.Length>=2?(Convert.ToDouble(a[0].Value),Convert.ToDouble(a[1].Value)):null;}
 static string San(string s)=>new string(s.Where(c=>char.IsLetterOrDigit(c)||c=='_').ToArray());
}
