namespace RofamaCad.Structural;
internal static class UnifiedBeamSolverV2
{
 public sealed record PointLoad(int Element,double X,double P);public sealed record Release(bool Start,bool End);public sealed record Result(double[] Displacement,double[] Reaction,double[] EndForce);
 public static Result Solve(double[] L,double[] EI,double[] w,bool[] fixV,bool[] fixR,Release[] releases,IReadOnlyList<PointLoad> points){
  int ne=L.Length;if(ne==0||EI.Length!=ne||w.Length!=ne||releases.Length!=ne||fixV.Length!=ne+1||fixR.Length!=ne+1)throw new ArgumentException("Dimensões inconsistentes no modelo.");if(L.Any(x=>x<=0)||EI.Any(x=>x<=0))throw new ArgumentException("L e EI devem ser positivos.");foreach(var p in points)if(p.Element<0||p.Element>=ne||p.X<0||p.X>L[p.Element])throw new ArgumentOutOfRangeException(nameof(points));
  int nd=2*(ne+1);var K=new double[nd,nd];var F=new double[nd];var elems=new ReleasedBeamElement.Condensed[ne];var maps=new int[ne][];
  for(int e=0;e<ne;e++){var ff=ReleasedBeamElement.UdlLoad(L[e],w[e]);foreach(var p in points.Where(p=>p.Element==e)){var fp=ReleasedBeamElement.PointLoad(L[e],p.X,p.P);for(int i=0;i<4;i++)ff[i]+=fp[i];}var c=ReleasedBeamElement.Build(L[e],EI[e],ff,releases[e].Start,releases[e].End);elems[e]=c;int[] full={2*e,2*e+1,2*e+2,2*e+3};maps[e]=c.Retained.Select(i=>full[i]).ToArray();for(int i=0;i<maps[e].Length;i++){F[maps[e][i]]+=c.F[i];for(int j=0;j<maps[e].Length;j++)K[maps[e][i],maps[e][j]]+=c.K[i,j];}}
  var fixedDofs=new HashSet<int>();for(int i=0;i<fixV.Length;i++){if(fixV[i])fixedDofs.Add(2*i);if(fixR[i])fixedDofs.Add(2*i+1);}var red=DisconnectedDofService.Detect(K,F);var active=red.Active.Where(i=>!fixedDofs.Contains(i)).ToArray();var u=new double[nd];if(active.Length>0){var Ka=Sub(K,active,active);var Fa=active.Select(i=>F[i]).ToArray();var ua=SolveLinear(Ka,Fa);for(int i=0;i<active.Length;i++)u[active[i]]=ua[i];}
  var R=Sub(Mul(K,u),F);var ef=new double[4*ne];for(int e=0;e<ne;e++){var ur=maps[e].Select(i=>u[i]).ToArray();var full=ReleasedBeamElement.Recover(elems[e],ur);var q=ReleasedBeamElement.EndForce(elems[e],full);Array.Copy(q,0,ef,4*e,4);}return new(u,R,ef);
 }
 static double[,] Sub(double[,] a,int[] r,int[] c){var z=new double[r.Length,c.Length];for(int i=0;i<r.Length;i++)for(int j=0;j<c.Length;j++)z[i,j]=a[r[i],c[j]];return z;}static double[] Sub(double[] a,double[] b)=>a.Zip(b,(x,y)=>x-y).ToArray();static double[] Mul(double[,] a,double[] x){var z=new double[a.GetLength(0)];for(int i=0;i<z.Length;i++)for(int j=0;j<x.Length;j++)z[i]+=a[i,j]*x[j];return z;}static double[,] Inv(double[,] a){int n=a.GetLength(0);var z=new double[n,2*n];for(int i=0;i<n;i++){for(int j=0;j<n;j++)z[i,j]=a[i,j];z[i,n+i]=1;}for(int k=0;k<n;k++){int p=k;for(int i=k+1;i<n;i++)if(Math.Abs(z[i,k])>Math.Abs(z[p,k]))p=i;if(Math.Abs(z[p,k])<1e-12)throw new InvalidOperationException("Matriz singular.");if(p!=k)for(int j=0;j<2*n;j++)(z[k,j],z[p,j])=(z[p,j],z[k,j]);double d=z[k,k];for(int j=0;j<2*n;j++)z[k,j]/=d;for(int i=0;i<n;i++)if(i!=k){double m=z[i,k];for(int j=0;j<2*n;j++)z[i,j]-=m*z[k,j];}}var r=new double[n,n];for(int i=0;i<n;i++)for(int j=0;j<n;j++)r[i,j]=z[i,n+j];return r;}static double[] SolveLinear(double[,] a,double[] b)=>Mul(Inv(a),b);
}